categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version 2.6 of snippy.
long_description: |
  Snippy finds variants between a haploid reference genome and your NGS sequence reads. It will find both substitutions and insertions/deletions (indels).
name: package_snippy_2_6
owner: simon-gladman
type: tool_dependency_definition
