categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version 1.2.10 of velvet.
long_description: |
  Velvet is a denovo genome assembly software written by D Zerbino. This is the 1.2.10 version.
name: package_velvet_1_2_10
owner: simon-gladman
remote_repository_url: https://github.com/Slugger70/galaxy_wrappers/tree/master/package_velvet_1_2_10
type: tool_dependency_definition
